# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f7d7d670489e4dd865a6f0fa93f4b0d18379c54be8fdf98d43eaa09ddbb348c01570f84a3126b04173321e1b007a7aba50c36f1c6dc1c1e75cad981b02264d

test:
  secret_key_base: 03578c90be31bba35b6e817ff77f611cd0476480128e49357417f9e56e9e2afb4b511d26a6f62749d4e3bbb901d1bd034ba9fdb75c5732fb81c4bc4f05fb508b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
